from pathlib import Path
from typing import Any


def write_promptfoo_config(
    out_dir: Path,
    *,
    agent_label: str,
    config: dict[str, Any],
) -> Path:
    """Minimal promptfoo YAML for `promptfoo eval` (reference / smoke)."""
    plugins = config.get("plugins") or ["default"]
    strategies = config.get("strategies") or ["basic"]
    path = out_dir / "promptfooconfig.yaml"
    # YAML as string to avoid PyYAML dependency for this path
    lines = [
        "# Auto-generated by AgentForge",
        f"# agent: {agent_label}",
        "description: AgentForge red-team",
        "prompts:",
        '  - "You are a helpful assistant. User: {{query}}"',
        "providers:",
        "  - id: echo",
        "    config:",
        "      label: mock-provider",
        "tests:",
    ]
    for i, p in enumerate(plugins):
        lines.append("  - vars:")
        lines.append(f'      query: "test {i} plugin={p}"')
    lines.append("defaultTest:")
    lines.append("  assert:")
    lines.append("    - type: javascript")
    lines.append('      value: "true"')
    lines.append("metadata:")
    lines.append(f"  strategies: {strategies!r}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
