#!/usr/bin/env bash
# AgentForge self-hosted installer
# Usage: curl -fsSL https://raw.githubusercontent.com/Sekoya88/AgentForge/main/scripts/install.sh | bash

set -euo pipefail

REPO="Sekoya88/AgentForge"
BRANCH="main"
RAW="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
INSTALL_DIR="${AGENTFORGE_DIR:-$HOME/.agentforge}"
COMPOSE_URL="${RAW}/docker-compose.prod.yml"
CADDYFILE_URL="${RAW}/Caddyfile"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

info()  { echo -e "${GREEN}[agentforge]${NC} $*"; }
warn()  { echo -e "${YELLOW}[agentforge]${NC} $*"; }
error() { echo -e "${RED}[agentforge] ERROR:${NC} $*" >&2; exit 1; }

# ── Dependency checks ────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || error "Docker is not installed. Visit https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is required. Update Docker Desktop or install the plugin."
command -v openssl >/dev/null 2>&1 || error "openssl is required but not found."
command -v curl >/dev/null 2>&1 || error "curl is required but not found."

info "Docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1) detected"

# ── Create install directory ─────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ── Download compose files ───────────────────────────────────────────────────
info "Downloading configuration..."
curl -fsSL "$COMPOSE_URL" -o docker-compose.prod.yml
curl -fsSL "$CADDYFILE_URL" -o Caddyfile

# ── Collect configuration ────────────────────────────────────────────────────
echo ""
echo "AgentForge configuration"
echo "────────────────────────"
read -rp "Domain name (leave blank for localhost HTTP): " DOMAIN
DOMAIN="${DOMAIN:-localhost}"

if [[ "$DOMAIN" == "localhost" ]]; then
  CADDY_ACME_EMAIL=""
  NEXT_PUBLIC_API_URL="http://localhost"
  warn "Running in localhost mode (HTTP only, no TLS). For production, provide a real domain."
else
  read -rp "Email for TLS certificate (Let's Encrypt): " CADDY_ACME_EMAIL
  NEXT_PUBLIC_API_URL="https://${DOMAIN}"
fi

# ── Generate secrets ─────────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
PG_PASSWORD=$(openssl rand -hex 16)
info "Secrets generated"

# ── Write .env.prod ──────────────────────────────────────────────────────────
cat > .env.prod <<EOF
# Generated by AgentForge installer on $(date)

POSTGRES_USER=forge
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=agentforge
DATABASE_URL=postgresql+asyncpg://forge:${PG_PASSWORD}@db:5432/agentforge

REDIS_URL=redis://redis:6379/0

JWT_SECRET_KEY=${JWT_SECRET}

CORS_ORIGINS=${NEXT_PUBLIC_API_URL}
CORS_ORIGIN_REGEX=

ALLOW_REGISTRATION=true

CADDY_DOMAIN=${DOMAIN}
CADDY_ACME_EMAIL=${CADDY_ACME_EMAIL}

NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_SENTRY_ENVIRONMENT=production

SENTRY_DSN=
MODAL_ENABLED=false
EOF

info "Configuration written to ${INSTALL_DIR}/.env.prod"

# ── Launch stack ─────────────────────────────────────────────────────────────
info "Starting AgentForge (this may take a few minutes on first run)..."
docker compose -f docker-compose.prod.yml --env-file .env.prod up -d

# ── Wait for backend health ──────────────────────────────────────────────────
info "Waiting for backend to be healthy..."
HEALTHY=false
for i in $(seq 1 30); do
  if docker compose -f docker-compose.prod.yml exec -T backend curl -sf http://localhost:8000/health >/dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 3
done

if [[ "$HEALTHY" != "true" ]]; then
  warn "Backend health check timed out. Check logs: docker compose -f ${INSTALL_DIR}/docker-compose.prod.yml logs backend"
fi

# ── Success message ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   AgentForge is running!                     ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║   URL:  ${NEXT_PUBLIC_API_URL}${NC}"
echo -e "${GREEN}║   Dir:  ${INSTALL_DIR}${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
info "Manage with: agentforge start | stop | update | logs | status"
info "Install CLI: brew tap Sekoya88/tap && brew install agentforge"
