#!/usr/bin/env bash
# AgentForge self-hosted installer
# Usage: curl -fsSL https://raw.githubusercontent.com/Sekoya88/AgentForge/main/scripts/install.sh | bash

set -euo pipefail

REPO="Sekoya88/AgentForge"
BRANCH="main"
RAW="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
INSTALL_DIR="${AGENTFORGE_DIR:-$HOME/.agentforge}"
COMPOSE_URL="${RAW}/docker-compose.prod.yml"
CADDYFILE_URL="${RAW}/Caddyfile"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

info()  { echo -e "${GREEN}[agentforge]${NC} $*"; }
warn()  { echo -e "${YELLOW}[agentforge]${NC} $*"; }
error() { echo -e "${RED}[agentforge] ERROR:${NC} $*" >&2; exit 1; }

# ── Dependency checks ────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || error "Docker is not installed. Visit https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is required. Update Docker Desktop or install the plugin."
command -v openssl >/dev/null 2>&1 || error "openssl is required but not found."
command -v curl >/dev/null 2>&1 || error "curl is required but not found."

info "Docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1) detected"

# ── Create install directory ─────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ── Download compose files ───────────────────────────────────────────────────
info "Downloading configuration..."
curl -fsSL "$COMPOSE_URL" -o docker-compose.prod.yml
curl -fsSL "$CADDYFILE_URL" -o Caddyfile

# ── Collect configuration (always read from /dev/tty so curl|bash works) ─────
echo ""
echo "AgentForge configuration"
echo "────────────────────────"
read -rp "Domain name (leave blank for localhost HTTP): " DOMAIN </dev/tty
DOMAIN="${DOMAIN:-localhost}"
# Strip characters unsafe for env values (allow alphanum, dots, hyphens only)
DOMAIN="${DOMAIN//[^a-zA-Z0-9.\-]/}"
DOMAIN="${DOMAIN:-localhost}"

if [[ "$DOMAIN" == "localhost" ]]; then
  CADDY_ACME_EMAIL=""
  NEXT_PUBLIC_API_URL="http://localhost"
  warn "Running in localhost mode (HTTP only, no TLS). For production, provide a real domain."
else
  read -rp "Email for TLS certificate (Let's Encrypt): " CADDY_ACME_EMAIL </dev/tty
  # Strip characters unsafe for env values (allow alphanum, @, dots, hyphens, plus, underscore)
  CADDY_ACME_EMAIL="${CADDY_ACME_EMAIL//[^a-zA-Z0-9@.\-+_]/}"
  NEXT_PUBLIC_API_URL="https://${DOMAIN}"
fi

# ── Generate secrets ─────────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
PG_PASSWORD=$(openssl rand -hex 16)
info "Secrets generated"

# ── Write .env.prod ──────────────────────────────────────────────────────────
# Use printf to avoid heredoc interpolation issues with user-supplied values
{
  printf '# Generated by AgentForge installer on %s\n\n' "$(date)"
  printf 'POSTGRES_USER=forge\n'
  printf 'POSTGRES_PASSWORD=%s\n' "$PG_PASSWORD"
  printf 'POSTGRES_DB=agentforge\n'
  printf 'DATABASE_URL=postgresql+asyncpg://forge:%s@db:5432/agentforge\n' "$PG_PASSWORD"
  printf '\nREDIS_URL=redis://redis:6379/0\n'
  printf '\nJWT_SECRET_KEY=%s\n' "$JWT_SECRET"
  printf '\nCORS_ORIGINS=%s\n' "$NEXT_PUBLIC_API_URL"
  printf 'CORS_ORIGIN_REGEX=\n'
  printf '\nALLOW_REGISTRATION=true\n'
  printf '\nCADDY_DOMAIN=%s\n' "$DOMAIN"
  printf 'CADDY_ACME_EMAIL=%s\n' "$CADDY_ACME_EMAIL"
  printf '\nNEXT_PUBLIC_API_URL=%s\n' "$NEXT_PUBLIC_API_URL"
  printf 'NEXT_PUBLIC_SENTRY_DSN=\n'
  printf 'NEXT_PUBLIC_SENTRY_ENVIRONMENT=production\n'
  printf '\nSENTRY_DSN=\n'
  printf 'MODAL_ENABLED=false\n'
} > .env.prod

info "Configuration written to ${INSTALL_DIR}/.env.prod"

# ── Launch stack ─────────────────────────────────────────────────────────────
info "Starting AgentForge (this may take a few minutes on first run)..."
docker compose -f docker-compose.prod.yml --env-file .env.prod up -d

# ── Wait for backend health ──────────────────────────────────────────────────
info "Waiting for backend to be healthy..."
HEALTHY=false
for i in $(seq 1 30); do
  if docker compose -f docker-compose.prod.yml exec -T backend curl -sf http://localhost:8000/health >/dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 3
done

if [[ "$HEALTHY" != "true" ]]; then
  warn "Backend health check timed out. Check logs with: docker compose -f ${INSTALL_DIR}/docker-compose.prod.yml logs backend"
fi

# ── Success message ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   AgentForge is running!                     ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║   URL:  ${NEXT_PUBLIC_API_URL}${NC}"
echo -e "${GREEN}║   Dir:  ${INSTALL_DIR}${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
info "Manage with: agentforge start | stop | update | logs | status"
info "Install CLI: brew tap Sekoya88/tap && brew install agentforge"
